{{!
    Force Sensitivity - Modifiers Table Template
    
    @package     IPS\forcesensitivity
    @subpackage  templates
    @author      jimstratus
    @copyright   2026
    @license     MIT
}}

<div class="acpFormWrapper">
    <h1 class="ipsType_pageTitle">{lang="fs_modifiers_title"}</h1>
    
    <div class="ipsBox">
        <div class="ipsBox_container">
            {$table|raw}
        </div>
    </div>
</div>
