{{!
    Force Sensitivity - Admin Settings Template
    
    @package     IPS\forcesensitivity
    @subpackage  templates
    @author      jimstratus
    @copyright   2026
    @license     MIT
}}

<div class="acpFormWrapper">
    <h1 class="ipsType_pageTitle">{lang="fs_settings_title"}</h1>
    
    <div class="ipsBox ipsMargin_top">
        <div class="ipsBox_container">
            {$form|raw}
        </div>
    </div>
</div>
